version: "3.8"
services:
  app: 
    build: django-crypto-app
    ports:
      - "8000:8000"
    volumes:
      - .:/django
    image: app.django
    container_name: crypto_app
    command: python manage.py runserver 0.0.0.0:8000